### ISSUE TITLE
Add catalog services to new tile-generator created tile.

### ISSUE THREAD

**Issue by spiegela** [thecodeteam/ecs-broker-tile#8]
Currently, the catalog configuration allows the operator to create up to 5 services, with a variable number of plans for each service. These services are then injected into the broker application by a BOSH release, which generates an `application.yml` file with each service and plan details.

When using tile generator process outlined in #15, The catalog services will need to be injected by environment variables. The format for these environment variables will look something like:

```yaml
...
  CATALOG_SERVICES_0_ID: 09cac1c6-1b0a-11e6-b6ba-3e1d05defe78
  CATALOG_SERVICES_0_NAME: ecs-namespace
  CATALOG_SERVICES_0_BINDABLE: true
  CATALOG_SERVICES_0_TAGS_0: s3
...
```

I'm not quite sure yet how to handle the variable number of _plans_ when injecting them as env variables...

This means, that the [ECS CF service broker](https://github.com/thecodeteam/ecs-cf-service-broker) may need to be updated to handle _"disabled"_ services.

Please refer to the changes in #7 (closed without merge) for catalog entries can should be removed.
